-- Medium-priority reliability, authorization and query-scope improvements.
-- Run this after apply_priority_fixes_and_surf_trip_stats.sql.

begin;

create index if not exists lessons_lesson_date_start_time_idx
  on public.lessons (lesson_date, start_time);

create index if not exists rental_slots_rental_date_start_time_idx
  on public.rental_slots (rental_date, start_time);

create index if not exists rental_registrations_slot_id_idx
  on public.rental_registrations (rental_slot_id);

create index if not exists lesson_member_attendance_checked_user_idx
  on public.lesson_member_attendance (user_id, lesson_id)
  where checked_in = true;

create index if not exists lesson_instructor_attendance_checked_user_idx
  on public.lesson_instructor_attendance (instructor_id, lesson_id)
  where checked_in = true;

create index if not exists profiles_pending_surf_level_review_idx
  on public.profiles (requested_surf_level_at)
  where requested_surf_level is not null;

-- ---------------------------------------------------------------------------
-- Club-owner and administrator governance
-- ---------------------------------------------------------------------------

create table if not exists public.club_governance (
  singleton boolean primary key default true check (singleton),
  owner_user_id uuid not null references public.profiles (id) on delete restrict,
  additional_admin_limit smallint not null default 3
    check (additional_admin_limit between 0 and 20),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.club_governance enable row level security;

do $seed_governance$
declare
  resolved_owner_id uuid;
  configured_owner_id uuid;
  current_additional_admin_count integer;
begin
  select profile.id
  into resolved_owner_id
  from public.profiles profile
  where lower(profile.email) = lower('tom.yeh.940402@gmail.com')
  order by profile.created_at asc
  limit 1;

  if resolved_owner_id is null then
    raise exception
      '找不到站主帳號 tom.yeh.940402@gmail.com；請先確認 profiles.email 再執行此 migration。';
  end if;

  insert into public.club_governance (
    singleton,
    owner_user_id,
    additional_admin_limit
  )
  values (true, resolved_owner_id, 3)
  on conflict (singleton) do nothing;

  select governance.owner_user_id
  into configured_owner_id
  from public.club_governance governance
  where governance.singleton = true;

  if configured_owner_id <> resolved_owner_id then
    raise exception '既有站主設定與 tom.yeh.940402@gmail.com 不一致，已停止執行。';
  end if;

  update public.profiles
  set role = 'admin', updated_at = now()
  where id = resolved_owner_id
    and role <> 'admin';

  select count(*)::integer
  into current_additional_admin_count
  from public.profiles profile
  where profile.role = 'admin'
    and profile.id <> resolved_owner_id;

  if current_additional_admin_count > 3 then
    raise exception '目前站主之外已有 % 位管理員，請先降至 3 位再執行。',
      current_additional_admin_count;
  end if;
end;
$seed_governance$;

revoke all on table public.club_governance from public, anon, authenticated;

create table if not exists public.member_role_audit_log (
  id bigint generated by default as identity primary key,
  target_user_id uuid not null,
  actor_user_id uuid null,
  previous_role text not null,
  new_role text not null,
  change_source text not null default 'profile_update',
  created_at timestamptz not null default now()
);

create index if not exists member_role_audit_log_target_created_idx
  on public.member_role_audit_log (target_user_id, created_at desc);

alter table public.member_role_audit_log enable row level security;

drop policy if exists "Admins can read member role audit log"
on public.member_role_audit_log;
create policy "Admins can read member role audit log"
on public.member_role_audit_log
for select
to authenticated
using (public.current_profile_role() = 'admin');

grant select on public.member_role_audit_log to authenticated;

create or replace function public.enforce_admin_governance()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  governance_row public.club_governance%rowtype;
  actor_role text;
  current_additional_admin_count integer;
begin
  select *
  into governance_row
  from public.club_governance
  where singleton = true
  for update;

  if governance_row.owner_user_id is null then
    raise exception '尚未設定站主帳號。';
  end if;

  if tg_op = 'DELETE' then
    if old.id = governance_row.owner_user_id then
      raise exception '站主帳號永遠不能被移除。';
    end if;

    if auth.uid() is not null then
      select profile.role::text
      into actor_role
      from public.profiles profile
      where profile.id = auth.uid();

      if old.id = auth.uid() then
        raise exception '不能移除自己的社員資料。';
      end if;

      if coalesce(actor_role, 'pending') not in ('officer', 'admin') then
        raise exception '只有幹部與管理員可以移除社員。';
      end if;

      if old.role = 'admin' and actor_role <> 'admin' then
        raise exception '只有管理員可以移除管理員。';
      end if;
    end if;

    return old;
  end if;

  if old.role is not distinct from new.role then
    return new;
  end if;

  if auth.uid() is not null and old.id = auth.uid() then
    raise exception '不能調整自己的身分。';
  end if;

  if new.id = governance_row.owner_user_id and new.role <> 'admin' then
    raise exception '站主帳號永遠必須保留管理員身分。';
  end if;

  if auth.uid() is not null then
    select profile.role::text
    into actor_role
    from public.profiles profile
    where profile.id = auth.uid();

    if coalesce(actor_role, 'pending') not in ('officer', 'admin') then
      raise exception '只有幹部與管理員可以調整社員身分。';
    end if;

    if (old.role = 'admin' or new.role = 'admin') and actor_role <> 'admin' then
      raise exception '只有管理員可以授予或移除管理員身分。';
    end if;
  end if;

  if old.role <> 'admin'
    and new.role = 'admin'
    and new.id <> governance_row.owner_user_id
  then
    select count(*)::integer
    into current_additional_admin_count
    from public.profiles profile
    where profile.role = 'admin'
      and profile.id <> governance_row.owner_user_id;

    if current_additional_admin_count >= governance_row.additional_admin_limit then
      raise exception '管理員名額已滿；站主之外最多只能有 % 位管理員。',
        governance_row.additional_admin_limit;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_admin_governance_on_profiles
on public.profiles;
create trigger enforce_admin_governance_on_profiles
before update of role or delete
on public.profiles
for each row
execute function public.enforce_admin_governance();

create or replace function public.audit_member_role_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.role is distinct from new.role then
    insert into public.member_role_audit_log (
      target_user_id,
      actor_user_id,
      previous_role,
      new_role,
      change_source
    )
    values (
      new.id,
      auth.uid(),
      old.role::text,
      new.role::text,
      coalesce(
        nullif(current_setting('app.member_role_change_source', true), ''),
        'profile_update'
      )
    );
  end if;

  return new;
end;
$$;

drop trigger if exists audit_member_role_change_on_profiles
on public.profiles;
create trigger audit_member_role_change_on_profiles
after update of role
on public.profiles
for each row
execute function public.audit_member_role_change();

create or replace function public.get_admin_governance()
returns table (
  owner_user_id uuid,
  additional_admin_count bigint,
  additional_admin_limit integer
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if coalesce(public.current_profile_role(), 'pending')
    not in ('officer', 'admin')
  then
    raise exception '只有幹部與管理員可以查看管理權限資訊。';
  end if;

  return query
  select
    governance.owner_user_id,
    count(profile.id)::bigint,
    governance.additional_admin_limit::integer
  from public.club_governance governance
  left join public.profiles profile
    on profile.role = 'admin'
    and profile.id <> governance.owner_user_id
  where governance.singleton = true
  group by governance.owner_user_id, governance.additional_admin_limit;
end;
$$;

create or replace function public.update_member_role(
  target_user_id uuid,
  target_role text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_role text := coalesce(public.current_profile_role(), 'pending');
  governance_row public.club_governance%rowtype;
  current_target_role text;
begin
  if auth.uid() is null then
    raise exception '請先登入。';
  end if;

  if actor_role not in ('officer', 'admin') then
    raise exception '只有幹部與管理員可以調整社員身分。';
  end if;

  if target_user_id = auth.uid() then
    raise exception '不能調整自己的身分。';
  end if;

  if target_role not in ('member', 'board_manager', 'officer', 'admin') then
    raise exception '社員身分無效。';
  end if;

  select *
  into governance_row
  from public.club_governance
  where singleton = true
  for update;

  if target_user_id = governance_row.owner_user_id then
    raise exception '站主帳號永遠不能被調整或移除。';
  end if;

  select profile.role::text
  into current_target_role
  from public.profiles profile
  where profile.id = target_user_id
  for update;

  if current_target_role is null then
    raise exception '找不到社員。';
  end if;

  if actor_role = 'officer'
    and (current_target_role = 'admin' or target_role = 'admin')
  then
    raise exception '只有管理員可以授予或移除管理員身分。';
  end if;

  perform set_config('app.member_role_change_source', 'member_role_rpc', true);

  update public.profiles
  set role = target_role, updated_at = now()
  where id = target_user_id;
end;
$$;

create or replace function public.approve_pending_members(target_user_ids uuid[])
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_current_profile_staff() then
    raise exception '只有幹部與管理員可以核准待審核社員。';
  end if;

  if target_user_ids is null
    or coalesce(array_length(target_user_ids, 1), 0) = 0
  then
    raise exception '請先選擇待審核社員。';
  end if;

  perform set_config(
    'app.member_role_change_source',
    'pending_member_approval',
    true
  );

  update public.profiles
  set
    role = 'member',
    surf_level = coalesce(surf_level, '初階'),
    updated_at = now()
  where id = any(target_user_ids)
    and role = 'pending';
end;
$$;

-- ---------------------------------------------------------------------------
-- Surf-level review: admins decide; advanced approval grants admin role.
-- ---------------------------------------------------------------------------

create or replace function public.approve_surf_level_request(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_level text;
  target_role text;
  governance_row public.club_governance%rowtype;
begin
  if coalesce(public.current_profile_role(), 'pending') <> 'admin' then
    raise exception '只有管理員可以核准衝浪程度。';
  end if;

  select *
  into governance_row
  from public.club_governance
  where singleton = true
  for update;

  select profile.requested_surf_level, profile.role::text
  into target_level, target_role
  from public.profiles profile
  where profile.id = target_user_id
  for update;

  if target_level is null then
    raise exception '目前沒有待審核的程度申請。';
  end if;

  if target_role not in ('member', 'board_manager', 'officer', 'admin') then
    raise exception '請先將申請人審核為正式社員，再處理程度申請。';
  end if;

  if target_level = '進階' then
    perform set_config(
      'app.member_role_change_source',
      'advanced_surf_level_approval',
      true
    );

    update public.profiles
    set
      surf_level = target_level,
      role = 'admin',
      requested_surf_level = null,
      requested_surf_level_at = null,
      updated_at = now()
    where id = target_user_id;
  else
    update public.profiles
    set
      surf_level = target_level,
      requested_surf_level = null,
      requested_surf_level_at = null,
      updated_at = now()
    where id = target_user_id;
  end if;
end;
$$;

create or replace function public.reject_surf_level_request(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(public.current_profile_role(), 'pending') <> 'admin' then
    raise exception '只有管理員可以拒絕衝浪程度申請。';
  end if;

  update public.profiles
  set
    requested_surf_level = null,
    requested_surf_level_at = null,
    updated_at = now()
  where id = target_user_id
    and requested_surf_level is not null;

  if not found then
    raise exception '目前沒有待審核的程度申請。';
  end if;
end;
$$;

create or replace function public.prevent_non_staff_high_surf_level_updates()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.surf_level is distinct from new.surf_level
    and new.surf_level in ('中進階', '進階')
    and coalesce(public.current_profile_role(), 'pending') <> 'admin'
  then
    raise exception '中進階與進階程度必須由管理員審核。';
  end if;

  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Attendance: eligibility only, with an explicit transactional promotion.
-- No time window is enforced.
-- ---------------------------------------------------------------------------

create or replace function public.promote_lesson_waitlist_member(
  target_lesson_id uuid,
  target_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  lesson_row public.lessons%rowtype;
  confirmed_count integer;
  first_waitlist_user_id uuid;
begin
  if not public.is_current_profile_staff() then
    raise exception '只有幹部與管理員可以正式遞補候補社員。';
  end if;

  select *
  into lesson_row
  from public.lessons
  where id = target_lesson_id
  for update;

  if lesson_row.id is null then
    raise exception '找不到社課。';
  end if;

  select count(*)::integer
  into confirmed_count
  from public.lesson_participants participant
  where participant.lesson_id = target_lesson_id
    and participant.status = 'confirmed';

  if confirmed_count >= lesson_row.capacity then
    raise exception '正取名額已滿，必須先釋出名額才能遞補。';
  end if;

  select participant.user_id
  into first_waitlist_user_id
  from public.lesson_participants participant
  where participant.lesson_id = target_lesson_id
    and participant.status = 'waitlist'
  order by participant.waitlist_order asc, participant.created_at asc
  limit 1
  for update;

  if first_waitlist_user_id is null then
    raise exception '目前沒有候補社員。';
  end if;

  if first_waitlist_user_id <> target_user_id then
    raise exception '必須依候補順序遞補。';
  end if;

  update public.lesson_participants
  set
    status = 'confirmed',
    waitlist_order = null,
    updated_at = now()
  where lesson_id = target_lesson_id
    and user_id = target_user_id
    and status = 'waitlist';

  with ordered as (
    select
      participant.id,
      row_number() over (
        order by participant.waitlist_order asc nulls last,
          participant.created_at asc,
          participant.id asc
      )::integer as new_order
    from public.lesson_participants participant
    where participant.lesson_id = target_lesson_id
      and participant.status = 'waitlist'
  )
  update public.lesson_participants participant
  set waitlist_order = -ordered.new_order
  from ordered
  where participant.id = ordered.id;

  update public.lesson_participants participant
  set waitlist_order = -participant.waitlist_order
  where participant.lesson_id = target_lesson_id
    and participant.status = 'waitlist'
    and participant.waitlist_order < 0;
end;
$$;

create or replace function public.set_lesson_member_attendance(
  target_lesson_id uuid,
  target_user_id uuid,
  target_checked_in boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception '請先登入。';
  end if;

  if not public.is_current_profile_staff() then
    raise exception '只有幹部與管理員可以簽到。';
  end if;

  if not exists (
    select 1
    from public.lessons lesson
    where lesson.id = target_lesson_id
  ) then
    raise exception '找不到社課。';
  end if;

  if not exists (
    select 1
    from public.lesson_participants participant
    where participant.lesson_id = target_lesson_id
      and participant.user_id = target_user_id
      and participant.status = 'confirmed'
  ) then
    raise exception '只有正取社員可以簽到；候補社員必須先正式遞補。';
  end if;

  insert into public.lesson_member_attendance (
    lesson_id,
    user_id,
    checked_in,
    checked_in_by,
    checked_in_at
  )
  values (
    target_lesson_id,
    target_user_id,
    target_checked_in,
    case when target_checked_in then auth.uid() else null end,
    case when target_checked_in then now() else null end
  )
  on conflict (lesson_id, user_id) do update
  set
    checked_in = excluded.checked_in,
    checked_in_by = excluded.checked_in_by,
    checked_in_at = excluded.checked_in_at;
end;
$$;

create or replace function public.set_lesson_instructor_attendance(
  target_lesson_id uuid,
  target_instructor_id uuid,
  target_checked_in boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception '請先登入。';
  end if;

  if not public.is_current_profile_staff() then
    raise exception '只有幹部與管理員可以簽到。';
  end if;

  if not exists (
    select 1
    from public.lesson_instructors instructor
    where instructor.lesson_id = target_lesson_id
      and instructor.instructor_id = target_instructor_id
  ) then
    raise exception '此社員不在本堂教學名單。';
  end if;

  insert into public.lesson_instructor_attendance (
    lesson_id,
    instructor_id,
    checked_in,
    checked_in_by,
    checked_in_at
  )
  values (
    target_lesson_id,
    target_instructor_id,
    target_checked_in,
    case when target_checked_in then auth.uid() else null end,
    case when target_checked_in then now() else null end
  )
  on conflict (lesson_id, instructor_id) do update
  set
    checked_in = excluded.checked_in,
    checked_in_by = excluded.checked_in_by,
    checked_in_at = excluded.checked_in_at;
end;
$$;

create or replace function public.check_in_all_lesson_instructors(
  target_lesson_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_current_profile_staff() then
    raise exception '只有幹部與管理員可以一鍵簽到。';
  end if;

  if not exists (
    select 1 from public.lessons lesson where lesson.id = target_lesson_id
  ) then
    raise exception '找不到社課。';
  end if;

  insert into public.lesson_instructor_attendance (
    lesson_id,
    instructor_id,
    checked_in,
    checked_in_by,
    checked_in_at
  )
  select
    target_lesson_id,
    instructor.instructor_id,
    true,
    auth.uid(),
    now()
  from public.lesson_instructors instructor
  where instructor.lesson_id = target_lesson_id
  on conflict (lesson_id, instructor_id) do update
  set
    checked_in = true,
    checked_in_by = auth.uid(),
    checked_in_at = now();
end;
$$;

-- ---------------------------------------------------------------------------
-- Aggregate attendance queries (avoid downloading all historical rows).
-- ---------------------------------------------------------------------------

create or replace function public.get_lesson_attendance_overview()
returns table (
  user_id uuid,
  attendance_count bigint,
  teaching_count bigint,
  started_lesson_count bigint
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_current_profile_staff() then
    raise exception '只有幹部與管理員可以查看出席統計。';
  end if;

  return query
  with started_lessons as (
    select lesson.id
    from public.lessons lesson
    where public.lesson_start_timestamp(lesson.lesson_date, lesson.start_time)
      <= (timezone('Asia/Taipei', now()))::timestamp
  ),
  attendance_events as (
    select attendance.user_id, attendance.lesson_id
    from public.lesson_member_attendance attendance
    join started_lessons lesson on lesson.id = attendance.lesson_id
    where attendance.checked_in = true

    union

    select attendance.instructor_id as user_id, attendance.lesson_id
    from public.lesson_instructor_attendance attendance
    join started_lessons lesson on lesson.id = attendance.lesson_id
    where attendance.checked_in = true
  ),
  attendance_counts as (
    select event.user_id, count(*)::bigint as attendance_count
    from attendance_events event
    group by event.user_id
  ),
  teaching_counts as (
    select attendance.instructor_id as user_id, count(distinct attendance.lesson_id)::bigint as teaching_count
    from public.lesson_instructor_attendance attendance
    join started_lessons lesson on lesson.id = attendance.lesson_id
    where attendance.checked_in = true
    group by attendance.instructor_id
  ),
  lesson_total as (
    select count(*)::bigint as started_lesson_count from started_lessons
  )
  select
    profile.id,
    coalesce(attendance_counts.attendance_count, 0),
    coalesce(teaching_counts.teaching_count, 0),
    lesson_total.started_lesson_count
  from public.profiles profile
  cross join lesson_total
  left join attendance_counts on attendance_counts.user_id = profile.id
  left join teaching_counts on teaching_counts.user_id = profile.id
  where profile.role in ('member', 'board_manager', 'officer', 'admin');
end;
$$;

create or replace function public.get_my_lesson_attendance_summary()
returns table (
  attended_count bigint,
  started_lesson_count bigint
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or not public.is_current_profile_member() then
    raise exception '只有正式社員可以查看出席統計。';
  end if;

  return query
  with started_lessons as (
    select lesson.id
    from public.lessons lesson
    where public.lesson_start_timestamp(lesson.lesson_date, lesson.start_time)
      <= (timezone('Asia/Taipei', now()))::timestamp
  ),
  my_attendance as (
    select attendance.lesson_id
    from public.lesson_member_attendance attendance
    join started_lessons lesson on lesson.id = attendance.lesson_id
    where attendance.user_id = auth.uid()
      and attendance.checked_in = true

    union

    select attendance.lesson_id
    from public.lesson_instructor_attendance attendance
    join started_lessons lesson on lesson.id = attendance.lesson_id
    where attendance.instructor_id = auth.uid()
      and attendance.checked_in = true
  )
  select
    (select count(*)::bigint from my_attendance),
    (select count(*)::bigint from started_lessons);
end;
$$;

create or replace function public.get_public_rental_schedule_range(
  target_start_date date,
  target_end_date date
)
returns table (
  id uuid,
  rental_date date,
  start_time time,
  end_time time,
  capacity integer,
  min_surf_level text,
  is_open boolean,
  registration_count integer,
  remaining_capacity integer
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if target_start_date is null
    or target_end_date is null
    or target_end_date < target_start_date
  then
    raise exception '租板日期範圍無效。';
  end if;

  if target_end_date - target_start_date > 62 then
    raise exception '公開租板日曆一次最多查詢 63 天。';
  end if;

  return query
  select
    slot.id,
    slot.rental_date,
    slot.start_time,
    slot.end_time,
    slot.capacity,
    slot.min_surf_level,
    slot.is_open,
    count(registration.id)::integer,
    greatest(slot.capacity - count(registration.id), 0)::integer
  from public.rental_slots slot
  left join public.rental_registrations registration
    on registration.rental_slot_id = slot.id
  where slot.rental_date between target_start_date and target_end_date
  group by
    slot.id,
    slot.rental_date,
    slot.start_time,
    slot.end_time,
    slot.capacity,
    slot.min_surf_level,
    slot.is_open
  order by slot.rental_date asc, slot.start_time asc;
end;
$$;

-- Keep the original no-argument RPC bounded for older deployed clients.
create or replace function public.get_public_rental_schedule()
returns table (
  id uuid,
  rental_date date,
  start_time time,
  end_time time,
  capacity integer,
  min_surf_level text,
  is_open boolean,
  registration_count integer,
  remaining_capacity integer
)
language sql
stable
security definer
set search_path = public
as $$
  select *
  from public.get_public_rental_schedule_range(
    (timezone('Asia/Taipei', now()))::date - 10,
    (timezone('Asia/Taipei', now()))::date + 52
  )
$$;

-- ---------------------------------------------------------------------------
-- Function privileges
-- ---------------------------------------------------------------------------

revoke all on function public.enforce_admin_governance() from public, anon, authenticated;
revoke all on function public.audit_member_role_change() from public, anon, authenticated;
revoke all on function public.get_admin_governance() from public, anon;
revoke all on function public.update_member_role(uuid, text) from public, anon;
revoke all on function public.approve_pending_members(uuid[]) from public, anon;
revoke all on function public.approve_surf_level_request(uuid) from public, anon;
revoke all on function public.reject_surf_level_request(uuid) from public, anon;
revoke all on function public.promote_lesson_waitlist_member(uuid, uuid) from public, anon;
revoke all on function public.set_lesson_member_attendance(uuid, uuid, boolean) from public, anon;
revoke all on function public.set_lesson_instructor_attendance(uuid, uuid, boolean) from public, anon;
revoke all on function public.check_in_all_lesson_instructors(uuid) from public, anon;
revoke all on function public.get_lesson_attendance_overview() from public, anon;
revoke all on function public.get_my_lesson_attendance_summary() from public, anon;
revoke all on function public.get_public_rental_schedule_range(date, date) from public, anon;
revoke all on function public.get_public_rental_schedule() from public, anon;

grant execute on function public.get_admin_governance() to authenticated;
grant execute on function public.update_member_role(uuid, text) to authenticated;
grant execute on function public.approve_pending_members(uuid[]) to authenticated;
grant execute on function public.approve_surf_level_request(uuid) to authenticated;
grant execute on function public.reject_surf_level_request(uuid) to authenticated;
grant execute on function public.promote_lesson_waitlist_member(uuid, uuid) to authenticated;
grant execute on function public.set_lesson_member_attendance(uuid, uuid, boolean) to authenticated;
grant execute on function public.set_lesson_instructor_attendance(uuid, uuid, boolean) to authenticated;
grant execute on function public.check_in_all_lesson_instructors(uuid) to authenticated;
grant execute on function public.get_lesson_attendance_overview() to authenticated;
grant execute on function public.get_my_lesson_attendance_summary() to authenticated;
grant execute on function public.get_public_rental_schedule_range(date, date) to anon, authenticated;
grant execute on function public.get_public_rental_schedule() to anon, authenticated;

commit;
